# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ed14f4ae9d7395d87c4527c1f1cf49d39071036051b50db6f6a69c38145240ff0c716e340b6347344355951d270c7a8e67b1f36207b0ee8f5bbda9229c2e3d2

test:
  secret_key_base: 8dacf40e609567b3a98480d9e96214809b75e7bb5969b84e18bbb429b47c4017b0fdd009691d96fa8ee9d4d7a2d443e6d8d4116241d73ce11ea5214fda93c241

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
